1차 커밋

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -18,6 +18,17 @@ jobs:
           echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" | sed 's/./& /g'
           echo "DOCKER_KEY=${{ secrets.DOCKER_TOKEN_KEY}}" | sed 's/./& /g'
 
+      - name: Check if secrets exist
+        run: |
+          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
+            echo "Error: DOCKER_USERNAME is not set"
+            exit 1
+          fi
+          if [ -z "${{ secrets.DOCKER_TOKEN_KEY }}" ]; then
+            echo "Error: DOCKER_TOKEN_KEY is not set"
+            exit 1
+          fi
+
       - name: Set up JDK 17
         uses: actions/setup-java@v1
         with:
